-- Generated by ~/.config/colors/render.sh — DO NOT EDIT.
-- Source: ~/.config/colors/palette.toml
-- Consumed by lua/plugins/dracula.lua to keep nvim's bg in sync with kitty.

return {
  primary    = "#cd9ae5",
  secondary  = "#340152",
  background = "#3a2987",
  view_bg    = "#0f0f14",
  border     = "#ffffff",
  accent     = "#0fcbf1",
  urgent     = "#E74C3C",
  fg         = "#ffffff",
  fg_muted   = "#b8b8b8",
}
